apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - welcome.pisang.my.id
    secretName: example-tls
  rules:
  - host: reza.fabryan@gmail.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
