name: "Docker Build Push"

on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      first:
        description: 'First Tag Version'
        required: true
        default: '1.0.1'
      latest:
        description: 'Latest Tag Version'
        required: true
        default: 'latest'

jobs:
    push_to_registry:
      name: Build and Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Build & Push Image
          run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker image build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ github.event.inputs.first }} -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ github.event.inputs.latest }} .
            docker push --all-tags ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

            
             
      



 
          
