name: "Docker Build Push"

on:
  push:
    branches: ['main']

jobs:
    push_to_registry:
      name: Build and Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Print version
          run: echo "Version ${{ inputs.version }}"
          shell: bash
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            image: ${{ secrets.DOCKER_IMAGE }}
        - name: Docker build
          run: "docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:1.0.1 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest ."
          shell: bash
        - name: Docker push
          run: docker push --all-tags ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
          shell: bash
