name: "Docker Build Push"

on:
  push:
    branches: ['main']

jobs:
    push_to_registry:
      name: Build and Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Build & Push Image
          run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker image build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:1.0.1 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest .
            docker push --all-tags ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
      
#      steps:
#        - name: Login to Docker Hub
#          uses: docker/login-action@v2
#          with:
#            username: ${{ secrets.DOCKER_USERNAME }}
#            password: ${{ secrets.DOCKER_PASSWORD }}
    
#        - name: Docker build
#          run: |
#            docker build -t ${{ secrets.DOCKER_USERNAME }}/simplepapptest:1.0.1 .

#        - name: Docker push
#          run: |
#            docker push --all-tags ${{ secrets.DOCKER_USERNAME }}/simplepapptest


 
          
